function(install_sample TARGETNAME )
	install(TARGETS ${TARGETNAME} 
		RUNTIME DESTINATION ${TARGETNAME}  CONFIGURATIONS Debug
		LIBRARY DESTINATION ${TARGETNAME}  CONFIGURATIONS Debug
		ARCHIVE DESTINATION ${TARGETNAME}  CONFIGURATIONS Debug
		COMPONENT ${TARGETNAME}
	)
	install(TARGETS ${TARGETNAME} 
		RUNTIME DESTINATION ${TARGETNAME}  CONFIGURATIONS Release
		LIBRARY DESTINATION ${TARGETNAME}  CONFIGURATIONS Release
		ARCHIVE DESTINATION ${TARGETNAME}  CONFIGURATIONS Release
		COMPONENT ${TARGETNAME}
	)
	install(FILES ${ARGN} DESTINATION ${TARGETNAME} COMPONENT ${TARGETNAME} )
	#LIST(APPEND CPACK_COMPONENTS_ALL ${TARGETNAME})
	#cpack_add_component(${TARGETNAME}
	#REQUIRED
	#)
endfunction(install_sample)

